name: Release

on:
  push:
    tags:
      # Semantic version tags: v1.0.0, v2.1.3, etc.
      - 'v*.*.*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-release:
    if: github.repository_owner == 'centennial-oss'
    uses: ./.github/workflows/release-build.yml
    secrets: inherit
    with:
      marketing_version: ${{ github.ref_name }}
      strip_version_v_prefix: true
      build_number: ${{ github.run_number }}
      build_info_arch: universal
      app_store_export_destination: upload
      export_options_suffix: -CI
      include_github_release: true
